### PR TITLE
Adds eff system

### PR DESCRIPTION
**Pull request by jO-Osko**
Adds new system `Eff` and corresponding benchmarks.

### CODE REVIEW

**Comment by dhil** [comment]
Thanks! LGTM. I will merge once the CI completes.

**Comment by jO-Osko** [comment]
Eff job name was still `bench-system-ocaml`, can you rerun the checks?

**Comment by dhil** [comment]
@kayceesrk Koka and Links both appeared to be blocked on some user input. I updated the Links image such that it works headlessly, so the CI must have pulled some stale data. Any idea on how I prime the cache?

**Comment by slindley** [comment]
Perhaps this helps: https://stackoverflow.com/questions/63521430/clear-cache-in-github-actions

**Comment by kayceesrk** [comment]
Don't know of an easy way to do this. I may be easiest to comment out the caching that I'd added, and then add it back in the next commit. Let me see if that works.

**Comment by kayceesrk** [comment]
> I updated the Links image such that it works headlessly, so the CI must have pulled some stale data.

Can you point me to the commit for this update?

**Comment by dhil** [comment]
> > I updated the Links image such that it works headlessly, so the CI must have pulled some stale data.
> 
> Can you point me to the commit for this update?

It should be the latest one on Dockerhub. I probably forgot to push the Dockerfile to main, did I?

**Comment by dhil** [comment]
I had forgotten to push the Dockerfile, sorry. Let's try again.

**Comment by dhil** [comment]
I've fixed the Koka image now too. I don't have rights to update this PR @jO-Osko can you merge in the new change such that I can rerun the CI?

**Comment by jO-Osko** [comment]
@dhil Rebased to main, it should pass now.
Strange, I ticked "allow edits by maintainers", shouldn't that give you access?

**Comment by dhil** [comment]
> @dhil Rebased to main, it should pass now.
> Strange, I ticked "allow edits by maintainers", shouldn't that give you access?

Thanks! I've thought so, but in my terminal I got "rejected" when I tried to pull this PR. I wouldn't rule out some configuration issue on my machine...

**Pull request merged**
